# -*- coding: utf-8 -*-
"""Untitled36.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1k2yln6GMFLUJD7V7mrGy03R0O-pWfONy
"""

import numpy as np
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans

# Data points
X = np.array([
    [1, 2],
    [1, 3],
    [2, 2],
    [2, 3],
    [8, 8],
    [8, 9],
    [9, 8],
    [9, 9]
])

# Apply K-Means
kmeans = KMeans(n_clusters=2, random_state=0, n_init=10)
labels = kmeans.fit_predict(X)

# Plot graph
plt.scatter(X[:, 0], X[:, 1], c=labels, s=100)

# Plot centroids
centers = kmeans.cluster_centers_
plt.scatter(centers[:, 0], centers[:, 1],
            marker='X', s=200)

plt.xlabel("X values")
plt.ylabel("Y values")
plt.title("K-Means Clustering")
plt.show()

import numpy as np
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans

# Customer data
X = np.array([
    [20, 80],
    [22, 85],
    [25, 78],
    [24, 82],
    [70, 20],
    [72, 25],
    [75, 22],
    [73, 28]
])

# Apply K-Means
kmeans = KMeans(n_clusters=2, random_state=0, n_init=10)
labels = kmeans.fit_predict(X)

# Plot graph
plt.scatter(X[:, 0], X[:, 1], c=labels, s=100)

# Plot centroids
centers = kmeans.cluster_centers_
plt.scatter(centers[:, 0], centers[:, 1],
            marker='X', s=200)

plt.xlabel("Annual Income")
plt.ylabel("Spending Score")
plt.title("Customer Segmentation using K-Means")
plt.show()

import numpy as np
import matplotlib.pyplot as plt
from sklearn.cluster import DBSCAN

# Data points
X = np.array([
    [1, 1],
    [1, 2],
    [2, 1],
    [2, 2],
    [8, 8],
    [8, 9],
    [9, 8],
    [9, 9],
    [20, 20]
])

# Apply DBSCAN
model = DBSCAN(eps=1.5, min_samples=3)
labels = model.fit_predict(X)

# Print cluster labels
print("Cluster labels:")
print(labels)

# Plot graph
plt.scatter(X[:, 0], X[:, 1], c=labels, s=100)

plt.xlabel("X values")
plt.ylabel("Y values")
plt.title("DBSCAN Clustering")
plt.show()

import numpy as np
import matplotlib.pyplot as plt
from sklearn.cluster import DBSCAN

# Customer data
# [Annual Income, Spending Score]
X = np.array([
    [20, 80],
    [21, 82],
    [22, 78],
    [23, 81],
    [40, 30],
    [41, 32],
    [42, 28],
    [43, 31],
    [80, 90]
])

# Apply DBSCAN
model = DBSCAN(eps=3, min_samples=3)
labels = model.fit_predict(X)

# Print labels
print("Cluster labels:")
print(labels)

# Plot graph
plt.scatter(X[:, 0], X[:, 1], c=labels, s=100)

plt.xlabel("Annual Income")
plt.ylabel("Spending Score")
plt.title("Customer Clustering using DBSCAN")
plt.show()