# -*- coding: utf-8 -*-
"""Untitled37.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LK7Rpz9aWOoOwbyW8JGzqG-6ATl1bcFG
"""

import pandas as pd
import seaborn as sns

# Load dataset
df = sns.load_dataset("iris")

# Display first 5 rows
print("First 5 rows:")
print(df.head())

# Display dataset shape
print("\nDataset Shape:")
print(df.shape)

# Display column names
print("\nColumn Names:")
print(df.columns)

# Check missing values
print("\nMissing Values:")
print(df.isnull().sum())

# Display statistical summary
print("\nStatistical Summary:")
print(df.describe())

import pandas as pd

# Create student dataset
data = {
    "Name": ["Bhanu", "Anu", "Ravi", "Sita", "Kiran"],
    "Marks": [85, 78, 92, 67, 88],
    "Age": [20, 21, 20, 22, 21]
}

# Create DataFrame
df = pd.DataFrame(data)

# Display dataset
print("Student Dataset:")
print(df)

# Display first 5 rows
print("\nFirst 5 rows:")
print(df.head())

# Display shape
print("\nDataset Shape:")
print(df.shape)

# Display column names
print("\nColumn Names:")
print(df.columns)

# Display statistical summary
print("\nStatistical Summary:")
print(df.describe())