# -*- coding: utf-8 -*-
"""Untitled45.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rHT2CgKcXwMLROUzw8mcubjCmnLziY7B
"""

import numpy as np
import matplotlib.pyplot as plt

from sklearn.cluster import KMeans, AgglomerativeClustering, DBSCAN

# Data points
X = np.array([
    [1, 1],
    [1, 2],
    [2, 1],
    [2, 2],
    [8, 8],
    [8, 9],
    [9, 8],
    [9, 9],
    [20, 20]
])

# ---------------- K-MEANS ----------------
kmeans = KMeans(n_clusters=2, random_state=0, n_init=10)
kmeans_labels = kmeans.fit_predict(X)

print("K-Means Labels:")
print(kmeans_labels)

# ---------------- HIERARCHICAL ----------------
hierarchical = AgglomerativeClustering(n_clusters=2)
hierarchical_labels = hierarchical.fit_predict(X)

print("\nHierarchical Labels:")
print(hierarchical_labels)

# ---------------- DBSCAN ----------------
dbscan = DBSCAN(eps=1.5, min_samples=3)
dbscan_labels = dbscan.fit_predict(X)

print("\nDBSCAN Labels:")
print(dbscan_labels)

# ----------- K-Means Graph -----------
plt.figure(figsize=(6, 4))
plt.scatter(X[:, 0], X[:, 1], c=kmeans_labels, s=100)
plt.title("K-Means Clustering")
plt.xlabel("X")
plt.ylabel("Y")
plt.show()

# ----------- Hierarchical Graph -----------
plt.figure(figsize=(6, 4))
plt.scatter(X[:, 0], X[:, 1], c=hierarchical_labels, s=100)
plt.title("Hierarchical Clustering")
plt.xlabel("X")
plt.ylabel("Y")
plt.show()

# ----------- DBSCAN Graph -----------
plt.figure(figsize=(6, 4))
plt.scatter(X[:, 0], X[:, 1], c=dbscan_labels, s=100)
plt.title("DBSCAN Clustering")
plt.xlabel("X")
plt.ylabel("Y")
plt.show()

import numpy as np
import matplotlib.pyplot as plt

from sklearn.cluster import KMeans
from sklearn.cluster import AgglomerativeClustering
from sklearn.cluster import DBSCAN

# Customer data
X = np.array([
    [20, 80],
    [22, 85],
    [25, 78],
    [24, 82],
    [40, 30],
    [41, 32],
    [42, 28],
    [43, 31],
    [80, 90]
])

# K-Means
kmeans = KMeans(n_clusters=2, random_state=0, n_init=10)
kmeans_labels = kmeans.fit_predict(X)

# Hierarchical Clustering
hierarchical = AgglomerativeClustering(n_clusters=2)
hierarchical_labels = hierarchical.fit_predict(X)

# DBSCAN
dbscan = DBSCAN(eps=3, min_samples=3)
dbscan_labels = dbscan.fit_predict(X)

# Print results
print("K-Means:")
print(kmeans_labels)

print("\nHierarchical:")
print(hierarchical_labels)

print("\nDBSCAN:")
print(dbscan_labels)

# K-Means graph
plt.figure(figsize=(6, 4))
plt.scatter(X[:, 0], X[:, 1], c=kmeans_labels, s=100)
plt.xlabel("Annual Income")
plt.ylabel("Spending Score")
plt.title("K-Means Customer Clustering")
plt.show()

# Hierarchical graph
plt.figure(figsize=(6, 4))
plt.scatter(X[:, 0], X[:, 1], c=hierarchical_labels, s=100)
plt.xlabel("Annual Income")
plt.ylabel("Spending Score")
plt.title("Hierarchical Customer Clustering")
plt.show()

# DBSCAN graph
plt.figure(figsize=(6, 4))
plt.scatter(X[:, 0], X[:, 1], c=dbscan_labels, s=100)
plt.xlabel("Annual Income")
plt.ylabel("Spending Score")
plt.title("DBSCAN Customer Clustering")
plt.show()