# -*- coding: utf-8 -*-
"""Untitled40.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10gX8wfBGY8F-llcW5XcUzZqtWa7SkS3T
"""

import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression

# Study hours
X = np.array([[1], [2], [3], [4], [5], [6], [7], [8]])

# 0 = Fail, 1 = Pass
y = np.array([0, 0, 0, 0, 1, 1, 1, 1])

# Create model
model = LogisticRegression()

# Train model
model.fit(X, y)

# Predict
predictions = model.predict(X)

print("Predicted Classes:")
print(predictions)

# Predict for a new student
hours = [[5.5]]
result = model.predict(hours)

print("Prediction for 5.5 study hours:")
if result[0] == 1:
    print("Pass")
else:
    print("Fail")

# Plot
plt.scatter(X, y)
plt.plot(X, model.predict_proba(X)[:, 1])
plt.xlabel("Study Hours")
plt.ylabel("Probability of Passing")
plt.title("Binary Logistic Regression")
plt.show()

import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression

# Study hours
X = np.array([
    [1], [2], [3],
    [4], [5], [6],
    [7], [8], [9]
])

# 0 = Low, 1 = Medium, 2 = High
y = np.array([
    0, 0, 0,
    1, 1, 1,
    2, 2, 2
])

# Create multinomial model
model = LogisticRegression(
    multi_class="multinomial",
    max_iter=1000
)

# Train model
model.fit(X, y)

# Predict
predictions = model.predict(X)

print("Predicted Classes:")
print(predictions)

# Predict for new students
new_students = np.array([[2.5], [5.5], [8.5]])

result = model.predict(new_students)

print("\nNew Student Predictions:")
print(result)

# Plot
plt.scatter(X, y, c=y)
plt.xlabel("Study Hours")
plt.ylabel("Class")
plt.title("Multinomial Logistic Regression")
plt.show()