# -*- coding: utf-8 -*-
"""Untitled44.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dEk9reIK0s3x92w5pYDN3RRHDb6gUFNk
"""

import numpy as np
from xgboost import XGBClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

# Student data
# [CGPA, Aptitude, Coding, Internship]
X = np.array([
    [8.5, 80, 85, 1],
    [7.2, 65, 60, 0],
    [9.0, 90, 95, 1],
    [6.5, 55, 50, 0],
    [8.0, 75, 80, 1],
    [7.0, 60, 65, 0],
    [9.2, 92, 90, 1],
    [6.8, 50, 55, 0],
    [8.7, 85, 88, 1],
    [7.5, 70, 68, 0]
])

# Placement result
# 0 = Not Placed, 1 = Placed
y = np.array([1, 0, 1, 0, 1, 0, 1, 0, 1, 0])

# Split data
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Create XGBoost model
model = XGBClassifier(
    n_estimators=100,
    max_depth=3,
    learning_rate=0.1,
    random_state=42,
    eval_metric="logloss"
)

# Train model
model.fit(X_train, y_train)

# Prediction
y_pred = model.predict(X_test)

# Accuracy
accuracy = accuracy_score(y_test, y_pred)

print("XGBoost Accuracy:", accuracy)

# Predict a new student
new_student = np.array([[8.3, 82, 80, 1]])

prediction = model.predict(new_student)

if prediction[0] == 1:
    print("New Student: Placed")
else:
    print("New Student: Not Placed")

import numpy as np
import pandas as pd
import lightgbm as lgb
import shap
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

# Student data
X = pd.DataFrame({
    "CGPA": [8.5, 7.2, 9.0, 6.5, 8.0,
             7.0, 9.2, 6.8, 8.7, 7.5],

    "Aptitude": [80, 65, 90, 55, 75,
                 60, 92, 50, 85, 70],

    "Coding": [85, 60, 95, 50, 80,
               65, 90, 55, 88, 68],

    "Internship": [1, 0, 1, 0, 1,
                   0, 1, 0, 1, 0]
})

# Placement result
y = np.array([1, 0, 1, 0, 1, 0, 1, 0, 1, 0])

# Split data
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Create LightGBM model
model = lgb.LGBMClassifier(
    n_estimators=100,
    learning_rate=0.1,
    max_depth=3,
    verbosity=-1
)

# Train model
model.fit(X_train, y_train)

# Prediction
y_pred = model.predict(X_test)

print("LightGBM Accuracy:",
      accuracy_score(y_test, y_pred))

# SHAP explainer
explainer = shap.TreeExplainer(model)

# Calculate SHAP values
shap_values = explainer.shap_values(X_test)

# SHAP graph
shap.summary_plot(
    shap_values,
    X_test,
    show=False
)

plt.title("SHAP Feature Importance")
plt.show()