# -*- coding: utf-8 -*-
"""Untitled38.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JuN3jnTQ2oHugqukISY6pFENqdiLte8E
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# Load Iris dataset
df = sns.load_dataset("iris")

# Display first 5 rows
print("First 5 rows:")
print(df.head())

# Basic information
print("\nDataset Information:")
print(df.info())

# Statistical summary
print("\nStatistical Summary:")
print(df.describe())

# Check missing values
print("\nMissing Values:")
print(df.isnull().sum())

# Histogram
plt.figure(figsize=(6, 4))
sns.histplot(df["sepal_length"], bins=10)
plt.title("Distribution of Sepal Length")
plt.xlabel("Sepal Length")
plt.ylabel("Frequency")
plt.show()

# Scatter plot
plt.figure(figsize=(6, 4))
sns.scatterplot(
    x="sepal_length",
    y="petal_length",
    hue="species",
    data=df
)
plt.title("Sepal Length vs Petal Length")
plt.show()

import pandas as pd
import matplotlib.pyplot as plt

# Create student dataset
data = {
    "Name": ["Bhanu", "Anu", "Ravi", "Sita", "Kiran"],
    "Marks": [85, 78, 92, 67, 88],
    "Age": [20, 21, 20, 22, 21]
}

# Create DataFrame
df = pd.DataFrame(data)

# Display dataset
print("Student Dataset:")
print(df)

# Statistical summary
print("\nStatistical Summary:")
print(df.describe())

# Check missing values
print("\nMissing Values:")
print(df.isnull().sum())

# Bar chart
plt.figure(figsize=(6, 4))
plt.bar(df["Name"], df["Marks"])
plt.title("Student Marks")
plt.xlabel("Students")
plt.ylabel("Marks")
plt.show()

# Scatter plot
plt.figure(figsize=(6, 4))
plt.scatter(df["Age"], df["Marks"])
plt.title("Age vs Marks")
plt.xlabel("Age")
plt.ylabel("Marks")
plt.show()