# -*- coding: utf-8 -*-
"""Untitled39.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XcgUuFMcyguYoTVoFwyGktnRt5e0vxUR
"""

import numpy as np
import matplotlib.pyplot as plt

# Input data: study hours
X = np.array([1, 2, 3, 4, 5], dtype=float)

# Output data: CGPA
y = np.array([5, 6, 7, 8, 9], dtype=float)

# Initial values
m = 0
c = 0

# Learning rate
learning_rate = 0.01

# Number of iterations
iterations = 1000

n = len(X)

# Gradient Descent
for i in range(iterations):

    # Prediction
    y_pred = m * X + c

    # Calculate gradients
    dm = (-2 / n) * np.sum(X * (y - y_pred))
    dc = (-2 / n) * np.sum(y - y_pred)

    # Update m and c
    m = m - learning_rate * dm
    c = c - learning_rate * dc

# Final prediction
y_pred = m * X + c

print("Slope (m):", m)
print("Intercept (c):", c)
print("Predicted CGPA:", y_pred)

# Plot graph
plt.scatter(X, y, label="Actual Data")
plt.plot(X, y_pred, label="Regression Line")

plt.xlabel("Study Hours")
plt.ylabel("CGPA")
plt.title("Gradient Descent - CGPA Regression")
plt.legend()
plt.show()

import numpy as np
import matplotlib.pyplot as plt

# Study hours
X = np.array([2, 3, 4, 5, 6], dtype=float)

# CGPA
y = np.array([5.5, 6.0, 7.0, 7.5, 8.5], dtype=float)

# Initial parameters
m = 0
c = 0

learning_rate = 0.01
epochs = 2000
n = len(X)

# Gradient Descent
for i in range(epochs):

    prediction = m * X + c

    error = prediction - y

    dm = (2 / n) * np.sum(error * X)
    dc = (2 / n) * np.sum(error)

    m = m - learning_rate * dm
    c = c - learning_rate * dc

# Prediction
predicted = m * X + c

print("Slope:", m)
print("Intercept:", c)

print("\nPredicted CGPA:")
print(predicted)

# Graph
plt.scatter(X, y, label="Actual CGPA")
plt.plot(X, predicted, label="Regression Line")

plt.xlabel("Study Hours")
plt.ylabel("CGPA")
plt.title("CGPA Prediction using Gradient Descent")
plt.legend()
plt.show()