# -*- coding: utf-8 -*-
"""Untitled41.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1O8fZ23xq22Rp8v_7Ry4ycUU-4t1WbfQA
"""

import numpy as np
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans

# Data points
X = np.array([
    [1, 2],
    [1, 3],
    [2, 2],
    [2, 3],
    [8, 8],
    [8, 9],
    [9, 8],
    [9, 9]
])

# Create K-Means model
kmeans = KMeans(n_clusters=2, random_state=0, n_init=10)

# Train the model
labels = kmeans.fit_predict(X)

# Print cluster labels
print("Cluster Labels:")
print(labels)

# Print centroids
print("\nCentroids:")
print(kmeans.cluster_centers_)

# Plot clusters
plt.scatter(X[:, 0], X[:, 1], c=labels, s=100)

# Plot centroids
centers = kmeans.cluster_centers_
plt.scatter(centers[:, 0], centers[:, 1],
            marker='X', s=200)

plt.xlabel("X values")
plt.ylabel("Y values")
plt.title("K-Means Clustering")
plt.show()

import numpy as np
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans

# Customer data
# [Annual Income, Spending Score]
X = np.array([
    [20, 80],
    [22, 85],
    [25, 78],
    [24, 82],
    [70, 20],
    [72, 25],
    [75, 22],
    [73, 28]
])

# Create K-Means model
kmeans = KMeans(n_clusters=2, random_state=0, n_init=10)

# Apply K-Means
labels = kmeans.fit_predict(X)

# Print labels
print("Customer Cluster Labels:")
print(labels)

# Print centroids
print("\nCentroids:")
print(kmeans.cluster_centers_)

# Plot graph
plt.scatter(X[:, 0], X[:, 1], c=labels, s=100)

# Plot centroids
centers = kmeans.cluster_centers_
plt.scatter(centers[:, 0], centers[:, 1],
            marker='X', s=200)

plt.xlabel("Annual Income")
plt.ylabel("Spending Score")
plt.title("Customer Segmentation using K-Means")
plt.show()