# -*- coding: utf-8 -*-
"""Untitled42.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17zbZEci7YjlyZ1Wl6ePnuMlyTqHFtKRP
"""

from sklearn.tree import DecisionTreeClassifier, plot_tree
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_iris
from sklearn.metrics import accuracy_score
import matplotlib.pyplot as plt

# Load Iris dataset
data = load_iris()

X = data.data
y = data.target

# Split data
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Decision Tree using Gini
model_gini = DecisionTreeClassifier(
    criterion="gini",
    random_state=42
)

model_gini.fit(X_train, y_train)

# Prediction
y_pred = model_gini.predict(X_test)

print("Gini Accuracy:",
      accuracy_score(y_test, y_pred))

# Decision Tree using Entropy
model_entropy = DecisionTreeClassifier(
    criterion="entropy",
    random_state=42
)

model_entropy.fit(X_train, y_train)

y_pred_entropy = model_entropy.predict(X_test)

print("Entropy Accuracy:",
      accuracy_score(y_test, y_pred_entropy))

# Display tree
plt.figure(figsize=(12, 8))
plot_tree(
    model_gini,
    feature_names=data.feature_names,
    class_names=data.target_names,
    filled=True
)

plt.title("Decision Tree using Gini")
plt.show()

from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_iris
from sklearn.metrics import accuracy_score
import matplotlib.pyplot as plt

# Load dataset
data = load_iris()

X = data.data
y = data.target

# Split dataset
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

depths = [1, 2, 3, 4, 5, 6]
accuracies = []

# Train trees with different depths
for depth in depths:

    model = DecisionTreeClassifier(
        max_depth=depth,
        random_state=42
    )

    model.fit(X_train, y_train)

    prediction = model.predict(X_test)

    accuracy = accuracy_score(y_test, prediction)

    accuracies.append(accuracy)

    print("Depth:", depth,
          "Accuracy:", accuracy)

# Plot graph
plt.plot(depths, accuracies, marker="o")

plt.xlabel("Tree Depth")
plt.ylabel("Accuracy")
plt.title("Decision Tree Depth Sweep")
plt.grid()
plt.show()