# -*- coding: utf-8 -*-
"""Untitled43.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10mpuR9n84h7B6pMmfK2Z12EUsPmAAJSD
"""

from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

# Load Iris dataset
data = load_iris()

X = data.data
y = data.target

# Split dataset
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Create Random Forest
model = RandomForestClassifier(
    n_estimators=100,
    oob_score=True,
    random_state=42
)

# Train model
model.fit(X_train, y_train)

# Prediction
y_pred = model.predict(X_test)

# Accuracy
accuracy = accuracy_score(y_test, y_pred)

print("Test Accuracy:", accuracy)

# OOB Score
print("OOB Score:", model.oob_score_)

# OOB Error
print("OOB Error:", 1 - model.oob_score_)

from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
import matplotlib.pyplot as plt

# Load dataset
data = load_iris()

X = data.data
y = data.target

# Split data
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Random Forest
model = RandomForestClassifier(
    n_estimators=100,
    max_features="sqrt",
    bootstrap=True,
    random_state=42
)

# Train model
model.fit(X_train, y_train)

# Prediction
y_pred = model.predict(X_test)

# Accuracy
accuracy = accuracy_score(y_test, y_pred)

print("Random Forest Accuracy:", accuracy)

print("Number of Trees:", model.n_estimators)

print("Features used for each split:",
      model.max_features)

print("Bootstrap Sampling:", model.bootstrap)

# Feature importance
importance = model.feature_importances_

print("\nFeature Importance:")
for feature, value in zip(data.feature_names, importance):
    print(feature, ":", value)

# Graph
plt.figure(figsize=(8, 5))
plt.bar(data.feature_names, importance)

plt.xlabel("Features")
plt.ylabel("Importance")
plt.title("Random Forest Feature Importance")
plt.xticks(rotation=30)
plt.show()